version: '2'

services:
  db:
    image: mongo:3.6.1
    ports:
      - 27017:27017
    command: --replSet rs1

  listner:
    image: sealsystems/mongodb-node-changestreams-sample
    command: /code/listen.js
    environment:
      ES_INDEX: seal-winston-log
      ES_NODE: ${ES_NODE}

  producer:
    image: sealsystems/mongodb-node-changestreams-sample
    command: /code/produce.js
    environment:
      ES_INDEX: seal-winston-log
      ES_NODE: ${ES_NODE}